// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ButtonScssNamespace {
  export interface IButtonScss {
    btn: string;
    'btn-base-inversed': string;
    'btn-bevel': string;
    'btn-bevel-inversed': string;
    'btn-ghost': string;
    'btn-ghost-inversed': string;
  }
}

declare const ButtonScssModule: ButtonScssNamespace.IButtonScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ButtonScssNamespace.IButtonScss;
};

export = ButtonScssModule;
