/* eslint-disable */
// prettier-ignore
// This file is automatically generated by typings-for-css-modules.
// Don't change it directly!

declare namespace ButtonScssNamespace {
  export interface IButtonScss {
    'btn': string;
    'btn-base-inversed': string;
    'btn-bevel': string;
    'btn-bevel-inversed': string;
    'btn-ghost': string;
    'btn-ghost-inversed': string;
  }
}

declare const ButtonScssModule: ButtonScssNamespace.IButtonScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ButtonScssNamespace.IButtonScss;
};

export = ButtonScssModule;
