/* eslint-disable */
// prettier-ignore
// This file is automatically generated by typings-for-css-modules.
// Don't change it directly!

declare namespace SwitchScssNamespace {
  export interface ISwitchScss {
    'checkbox-active-off': string;
    'checkbox-active-on': string;
    'switch': string;
    'switchLabel': string;
    'switchState': string;
    'switchToggle': string;
    'switchToggler': string;
  }
}

declare const SwitchScssModule: SwitchScssNamespace.ISwitchScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SwitchScssNamespace.ISwitchScss;
};

export = SwitchScssModule;
