/* eslint-disable */
// prettier-ignore
// This file is automatically generated by typings-for-css-modules.
// Don't change it directly!

declare namespace TypographyScssNamespace {
  export interface ITypographyScss {
    'accent': string;
    'h1': string;
    'h1-lg': string;
    'h1-sm': string;
    'h1-xl': string;
    'h1-xs': string;
    'main': string;
    'p': string;
    'p-lg': string;
    'p-sm': string;
    'p-xl': string;
    'p-xs': string;
  }
}

declare const TypographyScssModule: TypographyScssNamespace.ITypographyScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: TypographyScssNamespace.ITypographyScss;
};

export = TypographyScssModule;
